name: sonar.yml
on:
  pull_request: 
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Install dotnet sonar scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Install dotcover
        run: |
          dotnet tool install --global JetBrains.dotCover.CommandLineTools
  
      - name: Build + Analyze
        run: |
          dotnet-sonarscanner begin /k:"${{ secrets.PROJECT_KEY }}" /o:"${{ secrets.ORGANIZATION }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html
          dotnet build --no-incremental
          dotnet dotcover test --dcReportType=HTML
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"